
package com.tsystems.javaschool.logiweb.webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "InvalidRequestException", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/")
public class InvalidRequestException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidRequestException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidRequestException_Exception(String message, InvalidRequestException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidRequestException_Exception(String message, InvalidRequestException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.tsystems.javaschool.logiweb.webservices.InvalidRequestException
     */
    public InvalidRequestException getFaultInfo() {
        return faultInfo;
    }

}
