
package com.tsystems.javaschool.logiweb.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WsDriverImplService", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", wsdlLocation = "http://localhost:8080/logiweb/services/driver?wsdl")
public class WsDriverImplService
    extends Service
{

    private final static URL WSDRIVERIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.tsystems.javaschool.logiweb.webservices.WsDriverImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.tsystems.javaschool.logiweb.webservices.WsDriverImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/logiweb/services/driver?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/logiweb/services/driver?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSDRIVERIMPLSERVICE_WSDL_LOCATION = url;
    }

    public WsDriverImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsDriverImplService() {
        super(WSDRIVERIMPLSERVICE_WSDL_LOCATION, new QName("http://webservices.logiweb.javaschool.tsystems.com/", "WsDriverImplService"));
    }

    /**
     * 
     * @return
     *     returns WsDriver
     */
    @WebEndpoint(name = "WsDriverImplPort")
    public WsDriver getWsDriverImplPort() {
        return super.getPort(new QName("http://webservices.logiweb.javaschool.tsystems.com/", "WsDriverImplPort"), WsDriver.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsDriver
     */
    @WebEndpoint(name = "WsDriverImplPort")
    public WsDriver getWsDriverImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.logiweb.javaschool.tsystems.com/", "WsDriverImplPort"), WsDriver.class, features);
    }

}
