
package com.tsystems.javaschool.logiweb.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WsDriver", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsDriver {


    /**
     * 
     * @param cargoId
     */
    @WebMethod
    @RequestWrapper(localName = "setStatusPickedUpForCargo", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", className = "com.tsystems.javaschool.logiweb.webservices.SetStatusPickedUpForCargo")
    @ResponseWrapper(localName = "setStatusPickedUpForCargoResponse", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", className = "com.tsystems.javaschool.logiweb.webservices.SetStatusPickedUpForCargoResponse")
    public void setStatusPickedUpForCargo(
        @WebParam(name = "CargoId", targetNamespace = "")
        int cargoId);

    /**
     * 
     * @param cargoId
     */
    @WebMethod
    @RequestWrapper(localName = "setStatusDeliveredForCargoAndFinilizeOrderIfPossible", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", className = "com.tsystems.javaschool.logiweb.webservices.SetStatusDeliveredForCargoAndFinilizeOrderIfPossible")
    @ResponseWrapper(localName = "setStatusDeliveredForCargoAndFinilizeOrderIfPossibleResponse", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", className = "com.tsystems.javaschool.logiweb.webservices.SetStatusDeliveredForCargoAndFinilizeOrderIfPossibleResponse")
    public void setStatusDeliveredForCargoAndFinilizeOrderIfPossible(
        @WebParam(name = "CargoId", targetNamespace = "")
        int cargoId);

    /**
     * 
     * @param driverEmployeeId
     */
    @WebMethod
    @RequestWrapper(localName = "setStatusRestingForDriver", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", className = "com.tsystems.javaschool.logiweb.webservices.SetStatusRestingForDriver")
    @ResponseWrapper(localName = "setStatusRestingForDriverResponse", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", className = "com.tsystems.javaschool.logiweb.webservices.SetStatusRestingForDriverResponse")
    public void setStatusRestingForDriver(
        @WebParam(name = "DriverEmployeeId", targetNamespace = "")
        int driverEmployeeId);

    /**
     * 
     * @param driverEmployeeId
     * @return
     *     returns com.tsystems.javaschool.logiweb.webservices.DriverInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDriverInfo", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", className = "com.tsystems.javaschool.logiweb.webservices.GetDriverInfo")
    @ResponseWrapper(localName = "getDriverInfoResponse", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", className = "com.tsystems.javaschool.logiweb.webservices.GetDriverInfoResponse")
    public DriverInfo getDriverInfo(
        @WebParam(name = "DriverEmployeeId", targetNamespace = "")
        int driverEmployeeId);

    /**
     * 
     * @param driverEmployeeId
     */
    @WebMethod
    @RequestWrapper(localName = "setStatusDrivingForDriver", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", className = "com.tsystems.javaschool.logiweb.webservices.SetStatusDrivingForDriver")
    @ResponseWrapper(localName = "setStatusDrivingForDriverResponse", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", className = "com.tsystems.javaschool.logiweb.webservices.SetStatusDrivingForDriverResponse")
    public void setStatusDrivingForDriver(
        @WebParam(name = "DriverEmployeeId", targetNamespace = "")
        int driverEmployeeId);

    /**
     * 
     * @param driverEmployeeId
     * @param isBehindWheel
     */
    @WebMethod
    @RequestWrapper(localName = "shiftBegginedForDriver", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", className = "com.tsystems.javaschool.logiweb.webservices.ShiftBegginedForDriver")
    @ResponseWrapper(localName = "shiftBegginedForDriverResponse", targetNamespace = "http://webservices.logiweb.javaschool.tsystems.com/", className = "com.tsystems.javaschool.logiweb.webservices.ShiftBegginedForDriverResponse")
    public void shiftBegginedForDriver(
        @WebParam(name = "DriverEmployeeId", targetNamespace = "")
        int driverEmployeeId,
        @WebParam(name = "IsBehindWheel", targetNamespace = "")
        boolean isBehindWheel);

}
